# Generated by Django 5.0.14 on 2025-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
