# Generated by Django 5.0.14 on 2025-05-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PAYMENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'PICTURES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'REVIEWS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.IntegerField()),
                ('picture_url', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'Room_pictures',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='booking',
            table='BOOKINGS',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='HOTELS',
        ),
        migrations.AlterModelTable(
            name='room',
            table='ROOMS',
        ),
    ]
